### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.xuecheng-plus.com
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=x5v2mV&redirect_uri=http://www.xuecheng-plus.com



#### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123


###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=

###访问资源服务
GET http://localhost:63040/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzQxMjY5MTgsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjI5MjhmMTk1LTk2ZGEtNDU4OS04OTcxLTBlMzQ0ZWNhNWEzNiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.zVsnh79MRAgfpUyCvKcafA-KTjRHJT-UfJI5P4GcHrk
###通过网关访问资源服务
GET http://localhost:63010/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzQxMjQyMzksImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjY5NTE4NjRmLWM0MWYtNDNjZi04NjZhLTBiYWJhOGI4NjEwYiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.XFZD_AmcEanq-LRtK-v9CSIVLI-R0EkOpY1mYoHY9Fs
