### 添加选课
POST {{learning_host}}/learning/choosecourse/117
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzQyMzQyNjEsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjkxNjk1MzhiLTJhN2YtNDM1MC1iNTZjLTU3NGNjNGY3MjAzMCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.Vj2dW8IFNjUVOIF_x0wgMJALwSslwAPWizlGtqZO2Lc